### PR TITLE
Fix script names and script start/end prints, fix some spelling mistakes

### PR DESCRIPTION
**Pull request by Mixu78**

### CODE REVIEW

**Comment by lawfulrocky** [comment]
there is some  conflicts that need to be fix before i can merge

**Comment by Mixu78** [comment]
This probably breaks some history but whatever, it can merge now

**Comment by Mixu78** [comment]
Actually some stuff is probably broken, gotta look through this properly

**Comment by Mixu78** [comment]
Ok screw the merge conflicts, I'll just fix this later

**Pull request closed without merging**
